### ISSUE TITLE
On linux, underscores.  On WSL, dashes

### ISSUE THREAD

**Issue by legacy370** [kirillian/shiplane#74]
## Precheck
- Do a quick search through the Github Issues track to determine if your bug might already be submitted

## Environment
- OS **[Windows Subsystem for Linux]**
- Ruby **[2.6.6]**
- Shiplane **[0.2.28]**

## Current behavior

When running Shiplane on WSL, the bundle exec cap staging shiplane command fails.  It can't find the images it has just created.

## Expected behavior

Should work the same as on native Linux.
Reason -- on WSL, the default behavior is to use dashes in the image names, while shiplane is expecting underscores.
When I ran the command as  COMPOSE_COMPATIBILITY=true  bundle exec cap staging shiplane, it worked.

**Comment by kirillian** [comment]
This is actually expected behavior. It has nothing to do with WSL or not WSL though. It's cause is actually the Docker version that's installed in your system. You can read through some of the quirks in this stack overflow article: https://stackoverflow.com/questions/69464001/docker-compose-container-name-use-dash-instead-of-underscore.
